"""add columns to table

Revision ID: 134ad4b7f7ca
Revises: 67f5d67aea55
Create Date: 2024-10-08 09:06:47.781015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '134ad4b7f7ca'
down_revision = '67f5d67aea55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plants')
    # ### end Alembic commands ###
